[package]
name = "codec-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
codec-common = { path = "../common" }
codec-tcf = { path = "../tcf" }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"